# Generated by Django 3.0.6 on 2020-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200524_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskType',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='название трекера'),
        ),
    ]
