# Generated by Django 3.0.6 on 2020-05-24 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200524_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Comment'),
        ),
    ]
