# Generated by Django 3.0.6 on 2020-05-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_issue_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Issue'),
        ),
    ]
