# Generated by Django 3.0.6 on 2020-06-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20200610_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='priority',
            name='priorityname',
            field=models.CharField(max_length=32, null=True, verbose_name='название приоритета'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectname',
            field=models.CharField(max_length=200, null=True, verbose_name='название проекта'),
        ),
        migrations.AlterField(
            model_name='status',
            name='statusname',
            field=models.CharField(max_length=200, null=True, verbose_name='имя статуса'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='title',
            field=models.CharField(max_length=32, null=True, verbose_name='название трекера'),
        ),
    ]
